# 연습문제(실습형)

In [7]:
#1.다음코드는iris 데이터의독립변수(sepal_length, sepal_width, petal_length, petal_length)
#정보만갖도록한 코드입니다. 이를 이용해서주어진문제를해결하세요.

import numpy as np
from sklearn import datasets
iris= datasets.load_iris()
iris_data = iris.data  #독립변수 
iris.feature_names #독립변수의 column내용 
iris_data

#모든 알파벳을 숫자로  -->encoding 

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [24]:
#1 각 변수별 평균을 출력
np.mean(iris_data,axis=0) #열별평균    #shift+tab 도움말 

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [25]:
#2. 처음 다섯개 행으 출력
iris_data[:5]      #iris_data[:5,]     #판다스 데이터 프레임이 아니므로 head안됨

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [26]:
#3.처음 다섯개 행에서 마지막 열을 제외한 나머지 열을 출력
ex3 = iris_data[:5,:-1]
ex3 

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

In [27]:
#4. 처음 다섯개 행에서 마지막 열만 출력
ex4 = iris_data[:5,-1]
ex4

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [29]:
#5.3번 배열과 4번 배열을 원래 보양이 되도록 합치세요. 실행 결과는 2번의 결과와 같아야 합니다
np.c_[ex3,ex4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [30]:
np.column_stack((ex3,ex4))

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [31]:
np.hstack((ex3,ex4[:,np.newaxis]))   #2차원으로 바꾸면 hstack

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [33]:
#6. 처음 다섯 개 행을 이용해서 각 열 별로 평균보다 큰 값들만 출력
iris_sample = iris_data[:5]
iris_sample[iris_sample>np.mean(iris_sample,axis=0)] #인덱스에다 논리식

array([5.1, 3.5, 4.9, 1.5, 5. , 3.6])

In [34]:
iris_sample

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [35]:
np.mean(iris_sample, axis=0) #각 열 별로 평균

array([4.86, 3.28, 1.4 , 0.2 ])

# 연습문제(문제풀이형)

In [13]:
#1.다음 보기의 데이터가 있을 경우 print(a.sum(0))의 결과는?  # 답3번
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
print(a.sum(0))    #axis=0과 같음   행을 빼고, 열끼리 sum ***********

[12 15 18 21]


In [15]:
#2. a 데이터가 다음과 같을 때 다음 중 차원을 바꿀 수 있는 방법을 모두고르세요
#답:3번  resize  (1,2번은 return)
import numpy as np 
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 0., 4., 5.],
       [7., 3., 0., 7.],
       [3., 5., 6., 1.]])

In [16]:
a.shape          #reshape는 return   #a.T는 행과열을 바꿔줌 ()안애 매개변수 쓸 수 없음

(3, 4)

In [18]:
a.resize((2,6))
a

array([[4., 0., 4., 5., 7., 3.],
       [0., 7., 3., 5., 6., 1.]])

In [20]:
a.ravel()   

array([4., 0., 4., 5., 7., 3., 0., 7., 3., 5., 6., 1.])

In [ ]:
#3.다음 데이터에서 첫번째 행과 두번째 행만 뽑아내고 싶습니다. 빈칸에들어갈 내용으로 옳은 것을 고르세요.
import numpy as np
a = np.arrange(12).reshape(3,4)
답:1번
    
    #3번,4번은 6만 나옴

In [21]:
#4.다음 코드의 실행 결과는 ?  #답:2번 
a=np.array([1,2,3,4,5])
a[[1,3,4]]=0
a
#이해필요 ***************

array([1, 0, 3, 0, 0])

In [23]:
#5. 다음 두 배열 a, b를 출력의 예시처럼 만들고 싶을 때 빈 칸에 입력해야 할 내용으로 바른 것은?
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.c_[a,b]

#답:2번   np.c_[a,b]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [36]:
#5 선생님 풀이 버번

In [41]:

# 서술형5. (2)
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.c_[a,b]

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [40]:
# 위의 작업과 같은 결과를 수행하는 stack 함수들
np.dstack((a,b))

array([[[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

In [39]:
np.column_stack((a, b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [38]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [37]:
np.stack((a,b), axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])